config/routes.rb
Rails.application.routes.draw do
  root "artists#index"

  # get "artists" => "artists#index"
  # get "artists/:id" => "artists#show", as: :artist
  # delete "artists/:id" => "artists#destroy"
  resources :artists do #, only: [:index, :show, :destroy] do
    resources :songs #, only: [:create, :destroy]
  end
  # get "songs/new" => "songs#new", as: :new_song




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :image_url, length: { maximum: 255 }

  def self.order_by_name
    order(:name)
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates :title, presence: true
  validates :title, uniqueness: true
  # validates :artist_id, presence: true

  def self.order_by_title
    order(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist,  only: [:destroy, :show, :create]

  def index
    @artists = Artist.all
    @songs = Song.all
  end

  def show
    @songs = @artist.songs
    @song = Song.new
    # @song.artist_id = @artist.id
  end

  def destroy
    @artist.destroy
    redirect_to root_path, notice: 'Artist Killed.. huh What? Dead already!'
  end

  private

  def set_artist
   @artist = Artist.find_by_id(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :create, :destroy]

  def index
    @songs = Song.all
    @song = Song.new
  end

  def show
    @songs = Song.all
    @song = Song.find(params[:id])
  end

  # def create
  #   @song = Song.new(song_params)
  #   @song.artist_id = params[:artist_id]
  #   if @song.save
  #     redirect_to @song.artist, notice: "Song added"
  #   else
  #     redirect_to @song.artist
  #   end
  # end


  def create
    @song = Song.new(song_params)
    @song.artist_id = params[:artist_id]

      respond_to do |format|
        if @song.save
          format.html { redirect_to request.env["HTTP_REFERER"], notice: 'Song Added!' }
          format.json { render :show, status: :created, location: @songs }
        else
          format.html { redirect_to request.env["HTTP_REFERER"] }
          format.json { render json: @song.errors, status: :unprocessable_entity }
        end
      end
  end

  #
  # def destroy
  #   @song.destroy
  #   redirect_to @song.artist, notice: "Song removed."
  # end
  #
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to request.env["HTTP_REFERER"], notice: 'Song Removed.' }
      format.json { head :no_content }
    end
end

  private

  def song_params
    params.require(:song).permit(:title)
  end

  def set_artist
    @artist = Artist.find_by_id(params[:id])
  end

  def set_song
   @song = Song.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<% if notice.present? %>
      <div class="alert alert-info" role="alert">
        <%= notice %>
      </div>
<% end %>

<%= form_for [@artist, @song] do |f| %>
  <div class="form-group <%= @song.errors.any? ? 'has-error' : '' %>" id="formgroup-title">
    <%= f.text_field :title, placeholder: "Add Song", class: 'form-control', id: 'new-song' %>
    <% if @song.errors.any? %>
      <% @song.errors.full_messages.each do |message| %>
        <span class="help-block"><%= message %></span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/artists/index.html.erb
<h1>Artists' 27</h1>

<% @artists.each do |artist| %>
  <p><%= link_to artist.name, artist_path(artist.id) %></p>
<% end %>

app/views/artists/show.html.erb
<div class="bio">
  <h1><%= @artist.name %></h1>
  <%= image_tag @artist.image_url %>
</div>

  <div class="TodoList">
    <h2>Hit List</h2>
  </div>

    <table class="table table-striped" id="render">
      <%= render "artists/form", artist: @artist %>
    </table>

    <div class="rendersong">
      <%= render @song %>
    </div>
<hr>

<!-- <a class="btn btn-danger" data-confirm="Are you sure?" id="delete-all-songs"></span>Remove all songs</a> -->

<%= link_to "Remove Artist", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- Add jQuery -->
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Jura|Monoton" rel="stylesheet">
  </head>

  <body>

    <%= render "shared/navbar" %>
    <div class="container">
      <div class="jumbotron">
        <div class="yield">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Codaisseurify", root_path, class: "navbar-brand" %>
  </div>
</nav>

app/views/songs/_song.html.erb
<table class="table table-condensed" id="songList">
  <% if @artist.songs.any? %>
        <thead>
          <tr>
            <th> Title </th>
          </tr>
        </thead>
        <tbody>

        <% @artist.songs.each do |song| %>

              <tr>
                <td class="add song"><%= song.title %>
                <%= link_to "Remove Song",
                 artist_song_url(@artist, song), method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-default pull-right" %></td>
              </tr>

        <% end %>

      </tbody>
    <% else %>
      <p>Feel free to add your own songs!</p>
  <% end %>
</table>